version: "3.6"

networks:
  portfolio: 
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.1.0/24
  chain-backnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.35.160.96/27
