version: "3.6"

services:
#   smtp:
#     image: namshi/smtp
#     domainname: dev.jchein.name
#     hostname: mail
#     ports:
#       - 2525:25
#     networks:
#       - portfolio
#     environment:
#       SKEY_PATH: a
#       SCERTIFICATE_PATH: a
#       MAILNAME: mail.dev.jchein.name
#       PORT: 25

  minio1:
    image: minio/minio:RELEASE.2017-09-29T19-16-56Z
    restart: unless-stopped
    domainname: dev.jchein.name
    hostname: minio1
    ports:
      - 9401:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    networks:
      - portfolio
    volumes:
      - minio-data1:/data:delegated
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio2:
    image: minio/minio:RELEASE.2017-09-29T19-16-56Z
    restart: unless-stopped
    domainname: dev.jchein.name
    hostname: minio2
    ports:
      - 9402:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    networks:
      - portfolio
    volumes:
      - minio-data2:/data:delegated
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio3:
    image: minio/minio:RELEASE.2017-09-29T19-16-56Z
    restart: unless-stopped
    domainname: dev.jchein.name
    hostname: minio3
    ports:
      - 9403:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    networks:
      - portfolio
    volumes:
      - minio-data3:/data:delegated
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio4:
    image: minio/minio:RELEASE.2017-09-29T19-16-56Z
    restart: unless-stopped
    domainname: dev.jchein.name
    hostname: minio4
    ports:
      - 9404:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    networks:
      - portfolio
    volumes:
      - minio-data4:/data:delegated
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

volumes:
  minio-data1:
  minio-data2:
  minio-data3:
  minio-data4:

