volumes:
  - dev_volume
  - postgres_data
  
services:
  dev-machine: 
    build: git@github.com/eclipse/che-dockerfiles.git#master:recipes/debian_jdk8_node
    context: git@github.com/eclipse/che-dockerfiles.git#master:recipes/debian_jdk8_node
    volumes:
      - /dev_volume: /data
    ports:
      - 4000:4000

  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.18.0.RELEASE
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  
  kafka:
    image: eventuateio/eventuateio-local-kafka:0.18.0.RELEASE
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m
      - ZOOKEEPER_SERVERS=zookeeper:2181

  postgres:
    image: eventuateio/eventuateio-local-postgres:0.18.0.RELEASE
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=zumepizza
      - POSTGRES_PASSWORD=zumepizza
      - POSTGRES_DB=eventuate
  
  cdcservice:
    image: eventuateio/eventuateio-local-new-cdc-service:0.18.0.RELEASE
    links:
      - postgres
      - kafka
      - zookeeper
    ports:
      - 8080:8080
    volumes-from:
      - dev-machine
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/eventuate
      - SPRING_DATASOURCE_USERNAME=zumepizza
      - SPRING_DATASOURCE_PASSWORD=zumepizza
      - SPRING_DATASOURCE_TEST_ON_BORROW=true
      - SPRING_DATASOURCE_VALIDATION_QUERY="SELECT 1"
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING=zookeeper:2181
      - EVENTUATELOCAL_CDC_DB_USER_NAME=zumepizza
      - EVENTUATELOCAL_CDC_DB_PASSWORD=zumepizza
      - EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING=1000
      - EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING=100
      - EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS=500
      - EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS=500
      - EVENTUATE_DATABASE_SCHEMA=eventuate
      - SPRING_PROFILES_ACTIVE=EventuatePolling  

