#!/bin/sh

rm common/lib/metautils/datamodel/Builders.js
rm common/lib/metautils/datamodel/CloneConstructor.js
rm common/lib/metautils/datamodel/DataMixin.js
rm common/lib/metautils/datamodel/example.js
rm common/lib/metautils/datamodel/index.js
rm common/lib/metautils/datamodel/IndexedTypes.js
rm common/lib/metautils/datamodel/NoArgConstructor.js
rm common/lib/metautils/datamodel/OldBuilders.js
rm common/lib/metautils/decorators/index.js
rm common/lib/metautils/decorators/Retry.js
rm common/lib/metautils/decorators/Trace.js
rm common/lib/metautils/decorators/ValueConstructor.js
rm common/lib/metautils/index.js
rm common/lib/metautils/mixins/BaseDemo.js
rm common/lib/metautils/mixins/index.js
rm common/lib/metautils/mixins/LegacyMixins.js
rm common/lib/metautils/mixins/MixinConstructor.js
rm common/lib/metautils/mixins/Named.js
rm common/lib/metautils/validators/index.js
rm common/lib/metautils/validators/is-host-addr.js
rm common/lib/metautils/validators/is-longer-than.js
rm common/lib/metautils/validators/is-path.js
rm common/lib/metautils/validators/is-tcp-port.js
rm common/lib/type-utils/examples/Thingy.js
rm randomArt/canvas-and-plot-model.interface.js
rm randomArt/canvas-consumer.interface.js
rm randomArt/canvas-plotter.service.js
rm randomArt/canvas-provider.service.js
rm randomArt/canvas-writer.class.js
rm randomArt/canvas.d.js
rm randomArt/make-art.js
rm randomArt/name-model-adapter.class.js
rm randomArt/painting-context.interface.js
rm randomArt/point-map.class.js
rm randomArt/point.datamodel.js
rm randomArt/random-art-generator.service.js
rm randomArt/random-art-model.class.js
rm randomArt/random-art-source.service.js
rm randomArt/run-make-art.main.js
rm randomArt/task-content-adapter.interface.js
rm randomArt/task-loader.class.js
rm randomArt/write-to-file-context.interface.js
rm src/app/app-routing.module.js
rm src/app/app.module.js
rm src/app/core/core-routing.module.js
rm src/app/core/core.module.js
rm src/app/core/db-schema.object.js
rm src/app/core/db.js
rm src/app/core/feature/authz/core-authz.actions.js
rm src/app/core/feature/authz/core-authz.effecjs.ts
rm src/app/core/feature/authz/core-authz.models.js
rm src/app/core/feature/authz/core-authz.reducer.js
rm src/app/core/feature/authz/core-authz.selectors.js
rm src/app/core/feature/core-feature.reducer.js
rm src/app/core/feature/identity/core-identity.actions.js
rm src/app/core/feature/identity/core-identity.effecjs.ts
rm src/app/core/feature/identity/core-identity.models.js
rm src/app/core/feature/identity/core-identity.reducer.js
rm src/app/core/feature/identity/core-identity.selectors.js
rm src/app/core/feature/index.js
rm src/app/core/feature/layout/core-layout.actions.js
rm src/app/core/feature/layout/core-layout.models.js
rm src/app/core/feature/layout/core-layout.reducer.js
rm src/app/core/feature/layout/core-layout.selectors.js
rm src/app/core/identity/authenticated.guard.js
rm src/app/core/identity/fake-session.resolver.js
rm src/app/core/identity/index.js
rm src/app/core/identity/keycloak-authz.d.js
rm src/app/core/identity/keycloak-http-interceptor.service.js
rm src/app/core/identity/keycloak-http.service.js
rm src/app/core/identity/keycloak-internal-helper.interface.js
rm src/app/core/identity/keycloak-registry-entry.service.js
rm src/app/core/identity/keycloak-registry.service.js
rm src/app/core/identity/keycloak-session.resolver.js
rm src/app/core/identity/unidentified-guard.service.js
rm src/app/core/layout/app-root.component.js
rm src/app/core/layout/available-overlay.component.js
rm src/app/core/layout/index.js
rm src/app/core/layout/inner-navbar.component.js
rm src/app/core/layout/keycloak-session-component.js
rm src/app/core/layout/layout.component.js
rm src/app/core/layout/login-error.component.js
rm src/app/core/layout/login-modal.component.js
rm src/app/core/layout/menu-item.component.js
rm src/app/core/layout/nav-item.component.js
rm src/app/core/layout/nav-items.component.js
rm src/app/core/layout/page-not-found.component.js
rm src/app/core/layout/return-from-login.component.js
rm src/app/core/layout/sidenav.component.js
rm src/app/core/layout/toolbar.js
rm src/app/core/layout/top-toolbar.component.js
rm src/app/core/logging/my-console-listener-config.service.js
rm src/app/core/logging/my-custom-log-listener.service.js
rm src/app/custom-router-state-serializer.class.js
rm src/app/features/books/book-collection.actions.js
rm src/app/features/books/book-collection.effecjs.spec.ts
rm src/app/features/books/book-collection.effecjs.ts
rm src/app/features/books/book-collection.reducer.js
rm src/app/features/books/book-exisjs.guard.ts
rm src/app/features/books/book-feature.reducer.js
rm src/app/features/books/book-search.reducer.js
rm src/app/features/books/book.actions.js
rm src/app/features/books/book.effecjs.spec.ts
rm src/app/features/books/book.effecjs.ts
rm src/app/features/books/book.models.js
rm src/app/features/books/book.reducer.spec.js
rm src/app/features/books/book.reducer.js
rm src/app/features/books/books-routing.module.js
rm src/app/features/books/books.module.js
rm src/app/features/books/componenjs/book-authors.component.ts
rm src/app/features/books/componenjs/book-detail.component.ts
rm src/app/features/books/componenjs/book-main.container.ts
rm src/app/features/books/componenjs/book-navbar.component.ts
rm src/app/features/books/componenjs/book-preview-list.component.ts
rm src/app/features/books/componenjs/book-preview.component.ts
rm src/app/features/books/componenjs/book-search.component.ts
rm src/app/features/books/componenjs/book-sidenav.component.ts
rm src/app/features/books/componenjs/components.module.ts
rm src/app/features/books/google-books.service.spec.js
rm src/app/features/books/google-books.service.js
rm src/app/features/books/ptf-collection-page.container.js
rm src/app/features/books/ptf-find-book-page.container.js
rm src/app/features/books/ptf-selected-book-page.container.js
rm src/app/features/books/ptf-view-book-page.container.js
rm src/app/features/inventory/inventory-routing.module.js
rm src/app/features/inventory/inventory.module.spec.js
rm src/app/features/inventory/inventory.module.js
rm src/app/features/memes/phrase-generator.service.js
rm src/app/root-feature.reducer.js
rm src/app/shared/index.js
rm src/app/shared/layout-util/flex-spacer.directive.js
rm src/app/shared/layout-util/index.js
rm src/app/shared/layout-util/nav-item.component.js
rm src/app/shared/layout-util/no-content.component.js
rm src/app/shared/material.module.js
rm src/app/shared/navballs.directive.js
rm src/app/shared/pipes/add-commas.spec.js
rm src/app/shared/pipes/add-commas.js
rm src/app/shared/pipes/ellipsis.spec.js
rm src/app/shared/pipes/ellipsis.js
rm src/app/shared/pipes/pipes.module.js
rm src/app/shared/shared.module.spec.js
rm src/app/shared/shared.module.js
rm src/app/shared/utils.js
rm src/environments/environment.all.js
rm src/environments/environment.prod.js
rm src/environments/environment.js
rm src/main.js
rm src/polyfills.js
rm src/typings.d.js
rm src/vendor.js
