version: "3.6"

services:
  postgres:
    image: eventuateio/eventuateio-local-postgres:0.30.0.M8
    restart: unless-stopped
    domainname: dev.jchein.name
    hostname: postgres
    ports:
      - 25432:5432
    networks:
      - portfolio
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=eventuate
  
  cdcservice:
    image: eventuateio/eventuateio-local-new-cdc-service:0.30.0.M8
    restart: unless-stopped
    domainname: dev.jchein.name
    hostname: cdc-svc
    links:
      - postgres
      - kafka
      - zookeeper
    ports:
      - 8099:8080
    networks:
      - portfolio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/eventuate
      - SPRING_DATASOURCE_USERNAME=portfolio
      - SPRING_DATASOURCE_PASSWORD=portfolio
      - SPRING_DATASOURCE_TEST_ON_BORROW=true
      - SPRING_DATASOURCE_VALIDATION_QUERY="SELECT 1"
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING=zookeeper:2181
      - EVENTUATELOCAL_CDC_DB_USER_NAME=portfolio
      - EVENTUATELOCAL_CDC_DB_PASSWORD=portfolio
      - SPRING_PROFILES_ACTIVE=PostgresWal

volumes:
  postgres-data:
