version: "3.6"

services:
  # https://neo4j.com/docs/operations-manual/current/installation/docker/
  gallery-views-db:
    build: ./neo4j-graphql
    image: jheinnic/neo4j-graphql:0.0.1
    restart: unless-stopped
    domainname: dev.jchein.name
    hostname: gallery-views-db
    ports:
      - 27473:7473
      - 27474:7474
      - 27687:7687
    environment:
      - NEO4J_AUTH=neo4j/portfolio
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_maxSize=512M
      - NEO4J_dbms_txLog_rotation_retentionPolicy=100k txs
      - NEO4J_dbms_allowFormatMigration=true
      - NEO4J_dbms_unmanaged__extension__classes=org.neo4j.graphql=/graphql
    networks:
      - portfolio
    volumes:
      - gallery-views-data:/data:delegated
      - gallery-views-logs:/logs:delegated

  mongodb:
    image: mongo:3.0.4
    domainname: dev.jchein.name
    hostname: mongodb
    command: mongod --smallfiles
    ports:
      - 27017:27017
    networks:
      - portfolio
    volumes:
      - mongodb-data:/data:delegated

volumes:
  gallery-views-data:
  gallery-views-logs:
  mongodb-data:

