version: "3.6"

services:
  postgres:
    image: eventuateio/eventuateio-local-postgres:0.18.0.RELEASE
    restart: unless-stopped
    domainname: dev.jchein.name
    hostname: postgres
    ports:
      - 25432:5432
    networks:
      - portfolio
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=zumepizza
      - POSTGRES_PASSWORD=zumepizza
      - POSTGRES_DB=eventuate
  
  cdcservice:
    image: eventuateio/eventuateio-local-new-cdc-service:0.18.0.RELEASE
    restart: unless-stopped
    domainname: dev.jchein.name
    hostname: cdc-svc
    links:
      - postgres
      - kafka
      - zookeeper
    ports:
      - 8099:8080
    networks:
      - portfolio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/eventuate
      - SPRING_DATASOURCE_USERNAME=zumepizza
      - SPRING_DATASOURCE_PASSWORD=zumepizza
      - SPRING_DATASOURCE_TEST_ON_BORROW=true
      - SPRING_DATASOURCE_VALIDATION_QUERY="SELECT 1"
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING=zookeeper:2181
      - EVENTUATELOCAL_CDC_DB_USER_NAME=zumepizza
      - EVENTUATELOCAL_CDC_DB_PASSWORD=zumepizza
      - EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING=1000
      - EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING=100
      - EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS=500
      - EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS=500
      - EVENTUATE_DATABASE_SCHEMA=eventuate
      - SPRING_PROFILES_ACTIVE=EventuatePolling

volumes:
  postgres-data:
