version: "3.6"

services:
  vault-server:
    image: vault:1.0.1
    restart: unless-stopped
    domainname: dev.jchein.name
    hostname: vault-server
    ports:
      - 8200:8200/tcp
      - 8201:8201
    networks:
      - portfolio
    volumes:
      - vault-server-data:/vault/data:delegated
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 96ddf4bc-d217-f3ba-f9bd-017055595017
      VAULT_LOG_LEVEL: info
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_CACERT_: TBD
      VAULT_CAPATH_: TBD
      VAULT_CLIENT_CERT_: TBD
      VAULT_CLIENT_KEY_: TBD
      VAULT_TLS_SERVER_NAME_: TBD

volumes:
  vault-server-data:
